kind: DaemonSet
apiVersion: apps/v1
# name, namespace and labels are set at runtime
spec:
  template:
    spec:
      serviceAccountName: dns
      priorityClassName: system-node-critical
      containers:
      - name: dns
        # image is set at runtime
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: FallbackToLogsOnError
        command: [ "coredns" ]
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        ports:
        - containerPort: 5353
          name: dns
          protocol: UDP
        - containerPort: 5353
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 70Mi
      - name: dns-node-resolver
        # image is set at runtime
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          privileged: true
        volumeMounts:
        - name: hosts-file
          mountPath: /etc/hosts
        # env NAMESERVER and CLUSTER_DOMAIN are set at runtime
        command:
        - dns-operator
        - update-hosts
        - --interval
        - 5s
        - --hosts-file
        - /etc/hosts
        - --cluster-domain
        - $(CLUSTER_DOMAIN)
        - --nameserver
        - $(NAMESERVER)
        - --services
        - image-registry.openshift-image-registry.svc
        resources:
          requests:
            cpu: 10m
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux      
      volumes:
      - name: config-volume
        configMap:
        # Name is set at runtime
          items:
          - key: Corefile
            path: Corefile
      - name: hosts-file
        hostPath:
          path: /etc/hosts
          type: File
      tolerations:
      # DNS needs to run everywhere.
      - key: "node-role.kubernetes.io/master"
        operator: Exists
