# Cluster role for the operator itself.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-dns-operator:operator
  namespace: openshift-cluster-dns-operator
rules:
- apiGroups:
  - dns.openshift.io
  resources:
  - clusterdnses
  verbs:
  - list
  - watch

- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  verbs:
  - "*"

- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - serviceaccounts
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - delete

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
  - list
  - watch

# Mirrored from assets/dns/cluster-role.yaml
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  - pods
  - namespaces
  verbs:
  - list
  - watch
