# Binds the operator role to its Service Account.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator
subjects:
- kind: ServiceAccount
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: cluster-dns-operator
