apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-dns-operator
  template:
    metadata:
      labels:
        name: cluster-dns-operator
    spec:
      serviceAccountName: cluster-dns-operator
      restartPolicy: Always
      dnsPolicy: Default
      containers:
      - name: cluster-dns-operator
        image: openshift/origin-cluster-dns-operator:latest
        command:
        - cluster-dns-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: "cluster-dns-operator"
